#!/usr/bin/env python3
"""
Generate PROVIDE() linker directives and per-function section placements for fhprg.

Reads fhprg_syms.txt (addr + name) and fhprg.o (undefined symbols).
Outputs:
  tmp/fhprg_provides.ld  — PROVIDE() for all external data/function symbols
  tmp/fhprg_sections.ld  — per-function .text.FUN_xxx section placements

Usage:
    python3 tools/gen_fhprg_provides.py
"""
import re
import subprocess
import sys
from pathlib import Path

OUT = Path("tmp/fhprg_provides.ld")
SECTIONS_OUT = Path("tmp/fhprg_sections.ld")
SYMS_FILE = Path("tmp/fhprg_syms.txt")
NM = "arm-none-eabi-nm"


def find_object_files():
    """Find fhprg object files (monolithic or split)."""
    split_objs = sorted(Path("tmp").glob("fhprg_*.o"))
    if split_objs:
        return split_objs
    mono = Path("tmp/fhprg.o")
    if mono.exists():
        return [mono]
    return []

# Pattern: symbol name encodes its address (DAT_08058430 → 0x08058430)
ADDR_PATTERNS = [
    (r'^DAT_([0-9a-fA-F]{8})$', 'DAT'),
    (r'^LAB_([0-9a-fA-F]{8})$', 'LAB'),
    (r'^PTR_(?:.*_)?([0-9a-fA-F]{8})$', 'PTR'),  # PTR_xxx_ADDR or PTR_DAT_ADDR
    (r'^UNK_([0-9a-fA-F]{8})$', 'UNK'),
]


def get_undefined_symbols():
    """Extract undefined symbols from all object files."""
    objs = find_object_files()
    if not objs:
        print("ERROR: No fhprg object files found in tmp/")
        sys.exit(1)

    # Get all undefined symbols across all objects
    all_undef = set()
    all_defined = set()
    for obj in objs:
        # Undefined
        result = subprocess.run([NM, '-u', str(obj)], capture_output=True, text=True)
        for line in result.stdout.strip().split('\n'):
            line = line.strip()
            if not line:
                continue
            parts = line.split()
            if len(parts) >= 2 and parts[0] == 'U':
                all_undef.add(parts[1])
            elif len(parts) == 1:
                all_undef.add(parts[0])
        # Defined (to exclude cross-module refs)
        result = subprocess.run([NM, '--defined-only', str(obj)], capture_output=True, text=True)
        for line in result.stdout.strip().split('\n'):
            parts = line.strip().split()
            if len(parts) >= 3:
                all_defined.add(parts[2])

    # Only truly external: undefined but not defined in any module
    external = all_undef - all_defined
    print(f"Object files: {len(objs)}")
    print(f"Total undefined: {len(all_undef)}, defined across modules: {len(all_undef & all_defined)}")
    return sorted(external)


def extract_address(sym):
    """Try to extract an absolute address from a symbol name."""
    for pattern, _ in ADDR_PATTERNS:
        m = re.match(pattern, sym)
        if m:
            return int(m.group(1), 16)

    # func_0x0800bd9c pattern
    m = re.match(r'^func_0x([0-9a-fA-F]+)$', sym)
    if m:
        return int(m.group(1), 16)

    # PTR patterns with embedded addresses
    m = re.search(r'_([0-9a-fA-F]{8})$', sym)
    if m:
        addr = int(m.group(1), 16)
        # Sanity check: should be in plausible address range
        if addr >= 0x00010000:
            return addr

    return None


def main():
    syms = get_undefined_symbols()
    print(f"Total undefined symbols: {len(syms)}")

    lines = [
        "/* Auto-generated PROVIDE() for fhprg external symbols */",
        "/* Generated by tools/gen_fhprg_provides.py */",
        "",
    ]

    resolved = 0
    unresolved = []

    # Group by category
    categories = {}
    for sym in syms:
        addr = extract_address(sym)
        if addr is not None:
            lines.append(f"PROVIDE({sym} = 0x{addr:08x});")
            resolved += 1
            # Categorize
            prefix = sym.split('_')[0] if '_' in sym else sym
            categories[prefix] = categories.get(prefix, 0) + 1
        elif sym.startswith('__aeabi_'):
            unresolved.append(sym)
        elif sym.startswith('s_'):
            # String references: s_xxx_ADDR
            m = re.search(r'_([0-9a-fA-F]{8})$', sym)
            if m:
                addr = int(m.group(1), 16)
                lines.append(f"PROVIDE({sym} = 0x{addr:08x});")
                resolved += 1
            else:
                unresolved.append(sym)
        elif sym.startswith('coproc_'):
            # Coprocessor operations — these should be in ghidra_types.h
            unresolved.append(sym)
        elif sym == 'software_interrupt':
            # SVC instruction stub
            unresolved.append(sym)
        elif sym.startswith(('cRam', 'iRam', 'uRam')):
            # RAM references: cRam00000008 → address 0x00000008
            m = re.match(r'^[ciu]Ram([0-9a-fA-F]{8})$', sym)
            if m:
                addr = int(m.group(1), 16)
                lines.append(f"PROVIDE({sym} = 0x{addr:08x});")
                resolved += 1
            else:
                unresolved.append(sym)
        elif sym.startswith('stack0x'):
            # Stack offset references — these shouldn't be linker symbols
            # Provide them as dummy addresses (they're used as struct offsets)
            m = re.match(r'^stack(0x[0-9a-fA-F]+)$', sym)
            if m:
                val = int(m.group(1), 16)
                lines.append(f"PROVIDE({sym} = 0x{val:08x});")
                resolved += 1
            else:
                unresolved.append(sym)
        elif sym == 'SUB_00004b00':
            lines.append(f"PROVIDE({sym} = 0x00004b00);")
            resolved += 1
        elif sym == 'UnsignedSaturate':
            # ARM intrinsic — should be in ghidra_types.h
            unresolved.append(sym)
        elif sym.startswith('_local_'):
            # Local variable references leaked as symbols
            unresolved.append(sym)
        else:
            # Try generic address extraction
            m = re.search(r'([0-9a-fA-F]{8})', sym)
            if m:
                addr = int(m.group(1), 16)
                if addr >= 0x00010000:
                    lines.append(f"PROVIDE({sym} = 0x{addr:08x});")
                    resolved += 1
                else:
                    unresolved.append(sym)
            else:
                unresolved.append(sym)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text('\n'.join(lines) + '\n')

    print(f"Resolved: {resolved}")
    print(f"Unresolved: {len(unresolved)}")
    if unresolved:
        print("\nUnresolved symbols:")
        for sym in unresolved:
            print(f"  {sym}")

    print(f"\nWritten to {OUT}")

    # Generate per-function section placements
    generate_sections()


def parse_syms_file():
    """Parse fhprg_syms.txt: 'ADDR T NAME' per line."""
    funcs = []
    if not SYMS_FILE.exists():
        return funcs
    for line in SYMS_FILE.read_text().splitlines():
        parts = line.strip().split()
        if len(parts) >= 3:
            addr = int(parts[0], 16)
            name = parts[2]
            funcs.append((addr, name))
    return sorted(funcs, key=lambda x: x[0])


def get_defined_sections():
    """Get set of .text.XXX section names from all object files."""
    objs = find_object_files()
    sections = set()
    for obj in objs:
        result = subprocess.run(
            ['arm-none-eabi-objdump', '-h', str(obj)],
            capture_output=True, text=True
        )
        for line in result.stdout.splitlines():
            line = line.strip()
            parts = line.split()
            if len(parts) >= 2 and parts[1].startswith('.text.'):
                sections.add(parts[1])
    return sections


def generate_sections():
    """Generate tmp/fhprg_sections.ld with per-function section placements."""
    funcs = parse_syms_file()
    if not funcs:
        print("WARNING: No functions found in syms file, skipping sections generation")
        return

    sections = get_defined_sections()
    print(f"\nDefined .text.* sections in object: {len(sections)}")

    slines = [
        "/* Auto-generated per-function section placements */",
        "/* Generated by tools/gen_fhprg_provides.py */",
        "",
    ]

    placed = 0
    for addr, name in funcs:
        sec_name = f".text.{name}"
        if sec_name in sections:
            # Place at original address; SUBALIGN(1) prevents padding
            slines.append(f"  {sec_name} 0x{addr:08x} : SUBALIGN(1) {{ *({sec_name}) }}")
            placed += 1

    SECTIONS_OUT.write_text('\n'.join(slines) + '\n')
    print(f"Section placements: {placed}/{len(funcs)} functions")
    print(f"Written to {SECTIONS_OUT}")


if __name__ == '__main__':
    main()
